# Generated by Django 4.0.6 on 2023-03-28 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': True, 'verbose_name': 'Empelado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'managed': True, 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelTable(
            name='empleados',
            table='Empleados',
        ),
        migrations.AlterModelTable(
            name='empresas',
            table='Empresas',
        ),
    ]
